CREATE TABLE `internationalWarShelters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`country` enum('poland','czech','lithuania','latvia','estonia') NOT NULL,
	`city` varchar(100) NOT NULL,
	`type` enum('metro','bunker','basement','cave','other') NOT NULL,
	`lat` decimal(10,8) NOT NULL,
	`lng` decimal(11,8) NOT NULL,
	`address` text,
	`capacity` int NOT NULL,
	`currentOccupancy` int DEFAULT 0,
	`depth` int,
	`amenities` json,
	`phoneNumber` varchar(20),
	`website` varchar(500),
	`operatingHours` varchar(100),
	`accessibilityInfo` text,
	`isOpen` boolean DEFAULT true,
	`isVerified` boolean DEFAULT false,
	`source` varchar(100),
	`lastUpdatedBy` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `internationalWarShelters_id` PRIMARY KEY(`id`)
);
