// ─── Expanded Immediate Actions for Disasters ───────────────────────────────────
// This file contains enhanced disaster guides with 8+ immediate actions per disaster type

export const EXPANDED_EU_DISASTERS = {
  war: {
    code: "war",
    name: "War / Conflict",
    icon: "⚔️",
    region: "eu",
    immediateActions: [
      "🏃 Evacuate to nearest shelter or basement immediately - do NOT delay",
      "🪟 Stay away from windows and exterior walls to avoid shrapnel",
      "📍 Move to the center of the building, away from doors and windows",
      "👨‍👩‍👧‍👦 Keep all family members and pets together in one location",
      "📱 Turn off phone and avoid using it unless it's an emergency",
      "🔇 Listen to official emergency broadcasts on radio or TV",
      "🚪 Close and lock all doors and windows; seal gaps with tape if available",
      "💧 Fill bathtubs and containers with water immediately for drinking and sanitation",
      "🕯️ Locate flashlights, candles, and batteries - do NOT use candles if gas leak suspected",
      "📋 Gather important documents, medications, and valuables in one bag",
    ],
    evacuationSteps: [
      "Only evacuate if ordered by local authorities - do NOT leave without official order",
      "Use designated evacuation routes provided by authorities",
      "Avoid main roads and highways - use back roads if possible",
      "Travel during daylight hours if possible; avoid night travel",
      "Move to designated safe zones or shelters indicated by authorities",
      "Register with authorities upon arrival at shelter",
      "Do NOT return to your home until all-clear signal is given",
      "Help elderly, disabled, and vulnerable people during evacuation",
    ],
    safetyTips: [
      "Keep emergency supplies stocked at home and at work",
      "Have documents ready for evacuation (passport, ID, insurance papers)",
      "Listen to official broadcasts ONLY - do NOT believe rumors or social media",
      "Do NOT spread unverified information or rumors",
      "Help vulnerable neighbors, elderly, and those with disabilities",
      "Mark your home with your name if you evacuate",
      "Keep a list of emergency contacts written down (not just in phone)",
      "Know multiple evacuation routes from your home and workplace",
    ],
    whatToBring: [
      "Passport and important documents (ID, insurance, deeds, medical records)",
      "Medications and medical equipment (at least 30-day supply)",
      "Cash in multiple currencies (ATMs may not work)",
      "Phone chargers and backup power banks",
      "Water (minimum 3 liters per person for 3 days)",
      "Non-perishable food (canned goods, energy bars, dried fruits)",
      "Warm clothing, blankets, and sturdy shoes",
      "First aid kit and personal hygiene items",
      "Flashlight with extra batteries",
      "Portable radio (battery or hand-crank powered)",
    ],
    emergencyNumber: "112",
    helplineNumber: "Red Cross: +41 22 730 60 00",
    riskLevel: "Extreme",
  },
  bombing: {
    code: "bombing",
    name: "Bombing / Air Raid",
    icon: "💣",
    region: "eu",
    immediateActions: [
      "🚨 Go to nearest shelter or basement IMMEDIATELY when sirens sound",
      "🪟 Stay away from windows and exterior walls - move to interior rooms",
      "🛡️ Cover your head and neck with your hands or a pillow",
      "🏃 If outside, lie flat on the ground away from buildings and vehicles",
      "🚫 Do NOT look outside or go to windows to see what's happening",
      "👥 Move to the center of the building, away from walls and doors",
      "🔇 Stay quiet and listen for further instructions from authorities",
      "🧳 Keep your emergency bag with you at all times in the shelter",
      "💧 If in shelter, ration water and food - it may be a long wait",
      "🤝 Help others in the shelter, especially children and elderly",
    ],
    evacuationSteps: [
      "Wait for all-clear signal from authorities before leaving shelter",
      "Check for injuries and provide first aid if trained",
      "Exit building carefully - watch for debris and unstable structures",
      "Avoid debris, broken glass, and damaged areas",
      "Go to designated assembly points or shelters",
      "Do NOT touch unexploded ordnance or suspicious objects",
      "Report any injured people to emergency services",
      "Stay on designated paths - avoid areas with potential hazards",
    ],
    safetyTips: [
      "Know the location of nearest public shelter in your area",
      "Keep emergency supplies in your shelter (water, food, first aid)",
      "Stay tuned to emergency broadcasts - do NOT use phone unless emergency",
      "Stay calm and help others stay calm",
      "Do NOT use elevators - use stairs only",
      "Mark your shelter location and ensure family knows where to meet",
      "Practice shelter drills regularly with your family",
      "Keep a whistle in your pocket to signal for help if trapped",
    ],
    whatToBring: [
      "Important documents (ID, passport, insurance papers)",
      "Medications and medical equipment",
      "Water (at least 2 liters per person)",
      "Non-perishable food and energy bars",
      "Flashlight and extra batteries",
      "First aid kit and personal hygiene items",
      "Warm clothing and blankets",
      "Phone charger (if available)",
      "Whistle for signaling help",
      "Notebook and pen for communication",
    ],
    emergencyNumber: "112",
    helplineNumber: "Varies by country",
    riskLevel: "Extreme",
  },
  flood: {
    code: "flood",
    name: "Flood",
    icon: "🌊",
    region: "eu",
    immediateActions: [
      "🏃 Move to higher ground IMMEDIATELY - do NOT wait",
      "🚗 Do NOT attempt to cross flooded roads or bridges",
      "🔌 Turn off utilities (gas, electricity, water) if safe to do so",
      "🪟 Close all windows and doors to prevent water entry",
      "📦 Move valuables and important items to higher floors",
      "👨‍👩‍👧‍👦 Gather family members and pets and move to high ground",
      "📱 Call emergency services if trapped - do NOT try to swim or wade",
      "🧳 Take your emergency bag with essential documents and medications",
      "🚪 Lock your home before leaving if time permits",
      "📍 Go to designated evacuation centers or higher ground shelters",
    ],
    evacuationSteps: [
      "Follow evacuation orders from local authorities",
      "Use designated evacuation routes provided by authorities",
      "Go to higher ground or designated shelters",
      "Do NOT return to your home until all-clear is given",
      "Register with authorities at evacuation center",
      "Help elderly and disabled people during evacuation",
      "Document damage with photos for insurance purposes",
      "Wait for official clearance before returning home",
    ],
    safetyTips: [
      "Never drive through flooded areas - 'Turn Around, Don't Drown'",
      "Avoid contact with flood water - it may contain sewage and chemicals",
      "Do NOT allow children to play in flood water",
      "Be aware of hidden hazards under water (holes, debris, downed power lines)",
      "Watch for contaminated water that may cause illness",
      "Boil water before drinking if water supply is contaminated",
      "Disinfect all surfaces that came in contact with flood water",
      "Watch for weakened structures and unstable ground",
    ],
    whatToBring: [
      "Important documents (ID, insurance, property deeds)",
      "Medications and medical equipment",
      "Water (bottled or boiled)",
      "Non-perishable food",
      "Flashlight and batteries",
      "First aid kit",
      "Warm clothing and sturdy shoes",
      "Phone charger",
      "Toilet paper and hygiene items",
      "Protective gloves and masks",
    ],
    emergencyNumber: "112",
    helplineNumber: "Red Cross: +41 22 730 60 00",
    riskLevel: "High",
  },
  nuclear: {
    code: "nuclear",
    name: "Nuclear Emergency",
    icon: "☢️",
    region: "eu",
    immediateActions: [
      "🏃 Get inside a building IMMEDIATELY - preferably basement or center of building",
      "🚪 Close all windows and doors to seal out radioactive material",
      "🔌 Turn off ventilation systems (AC, fans) to prevent contaminated air entry",
      "📻 Listen to emergency broadcasts for instructions from authorities",
      "🧴 If outside, remove outer clothing and seal in a plastic bag",
      "🚿 Shower with soap and water if possible to remove radioactive particles",
      "💧 Drink only bottled water or water from sealed containers",
      "🏠 Shelter in place - do NOT evacuate unless ordered by authorities",
      "👨‍👩‍👧‍👦 Keep family together in the most protected room (basement, center of building)",
      "📱 Do NOT use phone unless absolutely necessary - keep lines open for emergency services",
    ],
    evacuationSteps: [
      "Only evacuate if ordered by local authorities",
      "Follow designated evacuation routes",
      "Do NOT use main roads if alternative routes are available",
      "Go to designated evacuation centers outside the danger zone",
      "Register with authorities at evacuation center",
      "Do NOT return to your home until all-clear is given",
      "Follow decontamination procedures at evacuation centers",
      "Comply with all instructions from emergency personnel",
    ],
    safetyTips: [
      "Potassium iodide tablets may be distributed - follow official instructions",
      "Stay indoors for extended period if nuclear incident occurs",
      "Avoid contaminated food and water",
      "Do NOT believe rumors - listen only to official broadcasts",
      "Avoid contact with people who may be contaminated",
      "Keep distance from windows and exterior walls",
      "Seal windows and doors with plastic sheeting and duct tape if needed",
      "Monitor local news for updates and all-clear signal",
    ],
    whatToBring: [
      "Important documents (ID, medical records)",
      "Medications (at least 30-day supply)",
      "Bottled water (at least 1 gallon per person per day)",
      "Non-perishable food (canned goods, energy bars)",
      "Flashlight and batteries",
      "First aid kit",
      "Protective clothing (long sleeves, pants, hat)",
      "Respirator or N95 masks",
      "Plastic sheeting and duct tape",
      "Potassium iodide tablets (if distributed)",
    ],
    emergencyNumber: "112",
    helplineNumber: "National radiation protection authority",
    riskLevel: "Extreme",
  },
  pandemic: {
    code: "pandemic",
    name: "Pandemic / Disease Outbreak",
    icon: "🦠",
    region: "eu",
    immediateActions: [
      "🏠 Stay home and isolate if you have symptoms or have been exposed",
      "🤒 Monitor your temperature and symptoms - report to health authorities if needed",
      "😷 Wear a mask when around others to prevent transmission",
      "🧼 Wash hands frequently with soap and water for at least 20 seconds",
      "🤝 Maintain at least 2 meters (6 feet) distance from others",
      "🧴 Use hand sanitizer (60% alcohol) when soap and water unavailable",
      "🚫 Do NOT touch your face, eyes, nose, or mouth",
      "🛒 Stock up on essential supplies - food, medications, hygiene items",
      "📱 Register with local health authorities if required",
      "🏥 Call health hotline if you develop symptoms - do NOT go to hospital without calling first",
    ],
    evacuationSteps: [
      "Follow quarantine or isolation orders from health authorities",
      "Do NOT leave your home except for essential medical care",
      "If hospitalization is needed, follow ambulance instructions",
      "Comply with all public health orders and restrictions",
      "Get tested if directed by health authorities",
      "Inform close contacts if you test positive",
      "Isolate for the duration recommended by health authorities",
      "Return to normal activities only after all-clear from health authorities",
    ],
    safetyTips: [
      "Get vaccinated if vaccine is available - follow official recommendations",
      "Wear appropriate masks in public settings",
      "Maintain good hygiene - wash hands, cover coughs and sneezes",
      "Avoid large gatherings and crowded places",
      "Stay informed through official health sources only",
      "Do NOT believe or spread misinformation about the disease",
      "Support vulnerable people (elderly, immunocompromised) by maintaining distance",
      "Practice respiratory etiquette - cough/sneeze into elbow or tissue",
    ],
    whatToBring: [
      "Medications (at least 30-day supply)",
      "Face masks (N95 or surgical masks)",
      "Hand sanitizer (60% alcohol or higher)",
      "Soap and disinfectant wipes",
      "Thermometer",
      "Pain relievers and fever reducers",
      "Cough drops and throat lozenges",
      "Non-perishable food and water",
      "Tissues and paper towels",
      "Gloves (nitrile or latex)",
    ],
    emergencyNumber: "112",
    helplineNumber: "National health hotline (varies by country)",
    riskLevel: "High",
  },
};

export const EXPANDED_US_DISASTERS = {
  wildfire: {
    code: "wildfire",
    name: "Wildfire",
    icon: "🔥",
    region: "us",
    immediateActions: [
      "🏃 Evacuate IMMEDIATELY if ordered by authorities - do NOT delay",
      "🚗 Leave on main roads with headlights on - do NOT use back roads",
      "🧳 Take your emergency bag with important documents and medications",
      "👨‍👩‍👧‍👦 Ensure all family members and pets are with you before leaving",
      "🪟 Close all windows and doors - turn off gas at meter if time permits",
      "💧 Fill your vehicle's gas tank - gas stations may be closed",
      "📱 Listen to emergency alerts on your phone or local radio",
      "🏠 Leave lights on so firefighters can see your home",
      "🧢 Wear long sleeves, pants, and sturdy shoes for protection",
      "🚫 Do NOT attempt to fight the fire or stay to protect your property",
    ],
    evacuationSteps: [
      "Follow designated evacuation routes provided by authorities",
      "Do NOT use shortcuts or back roads - main roads are safer",
      "Drive slowly and carefully - visibility may be poor",
      "Turn on headlights and keep them on",
      "Go to designated evacuation centers or shelters",
      "Register with authorities at evacuation center",
      "Do NOT return to your home until all-clear is given",
      "Help others evacuate if you are able to do so safely",
    ],
    safetyTips: [
      "Wear N95 masks to protect from smoke",
      "Stay indoors with windows closed during fire",
      "Use air purifiers if available",
      "Keep medications and important documents ready",
      "Have a full tank of gas before fire season",
      "Clear brush and dead trees from around your home",
      "Keep gutters clean and roof clear of debris",
      "Have a family communication plan in place",
    ],
    whatToBring: [
      "Important documents (ID, insurance, deeds)",
      "Medications and medical equipment",
      "Phone chargers and backup power banks",
      "Cash and credit cards",
      "Irreplaceable photos and heirlooms",
      "Pet carriers and pet supplies",
      "Water and non-perishable food",
      "Flashlight and batteries",
      "First aid kit",
      "Comfortable walking shoes",
    ],
    emergencyNumber: "911",
    helplineNumber: "1-800-621-3362",
    riskLevel: "High",
  },
  earthquake: {
    code: "earthquake",
    name: "Earthquake",
    icon: "🌍",
    region: "us",
    immediateActions: [
      "🛡️ DROP to hands and knees IMMEDIATELY when shaking starts",
      "📦 COVER your head and neck under a sturdy desk or table",
      "🤝 HOLD ON to your shelter and protect your head with your hands",
      "🪟 Stay away from windows, mirrors, and heavy objects that could fall",
      "🏢 If in building, stay inside - do NOT run outside",
      "🚗 If driving, pull over safely and stay in vehicle with seatbelt on",
      "🏃 If outside, move away from buildings, power lines, and trees",
      "🧱 Do NOT stand in doorways - this is a myth, stay under sturdy furniture",
      "🕐 Wait for shaking to stop completely before moving",
      "🏠 If trapped, do NOT shout - tap on pipes or walls to signal rescuers",
    ],
    evacuationSteps: [
      "Check for injuries and provide first aid",
      "Inspect your home for damage (gas leaks, structural damage)",
      "Turn off gas if you smell it - do NOT use open flames",
      "Do NOT use elevators - use stairs only",
      "Exit building carefully if safe - watch for fallen debris",
      "Go to designated assembly points or shelters",
      "Do NOT enter damaged buildings",
      "Help others if you are able to do so safely",
    ],
    safetyTips: [
      "Secure heavy furniture to walls before earthquake",
      "Keep emergency supplies in multiple locations",
      "Know how to turn off utilities (gas, water, electricity)",
      "Practice DROP, COVER, HOLD ON regularly with family",
      "Stay away from damaged buildings",
      "Be prepared for aftershocks",
      "Do NOT use phone unless absolutely necessary",
      "Listen to official emergency broadcasts",
    ],
    whatToBring: [
      "First aid kit",
      "Water (1 gallon per person per day for 3 days)",
      "Non-perishable food",
      "Flashlight and extra batteries",
      "Portable radio",
      "Important documents",
      "Medications",
      "Sturdy shoes and gloves",
      "Whistle for signaling help",
      "Wrench or pliers to turn off utilities",
    ],
    emergencyNumber: "911",
    helplineNumber: "1-800-621-3362",
    riskLevel: "High",
  },
  hurricane: {
    code: "hurricane",
    name: "Hurricane / Typhoon",
    icon: "🌀",
    region: "us",
    immediateActions: [
      "🏃 Evacuate IMMEDIATELY if ordered by authorities",
      "🏠 If not evacuating, move to interior room on lowest floor",
      "🪟 Close all windows and doors - board up windows if possible",
      "🛢️ Bring outdoor items inside or secure them",
      "💧 Fill bathtubs and containers with water",
      "🔌 Turn off utilities if ordered by authorities",
      "📱 Charge all devices and have battery-powered radio ready",
      "🧳 Have emergency bag packed and ready to go",
      "👨‍👩‍👧‍👦 Keep family and pets together",
      "🚗 Fill vehicle's gas tank - gas stations may close",
    ],
    evacuationSteps: [
      "Follow evacuation orders from authorities",
      "Use designated evacuation routes",
      "Go to designated shelters or higher ground",
      "Do NOT return to your home until all-clear is given",
      "Register with authorities at evacuation center",
      "Help elderly and disabled people during evacuation",
      "Document damage with photos for insurance",
      "Wait for official clearance before returning home",
    ],
    safetyTips: [
      "Know your evacuation zone and routes",
      "Have multiple ways to receive emergency alerts",
      "Secure outdoor items or bring them inside",
      "Keep important documents in waterproof container",
      "Know how to turn off utilities",
      "Have cash on hand - ATMs may not work",
      "Keep medications in waterproof container",
      "Stay informed through official sources only",
    ],
    whatToBring: [
      "Important documents in waterproof container",
      "Medications and medical equipment",
      "Water (1 gallon per person per day)",
      "Non-perishable food",
      "Flashlight and batteries",
      "First aid kit",
      "Cash and credit cards",
      "Phone charger",
      "Change of clothing",
      "Sturdy shoes",
    ],
    emergencyNumber: "911",
    helplineNumber: "1-800-621-3362",
    riskLevel: "High",
  },
  tornado: {
    code: "tornado",
    name: "Tornado",
    icon: "🌪️",
    region: "us",
    immediateActions: [
      "🏃 Go to safe room or basement IMMEDIATELY when tornado warning issued",
      "🛡️ Get to interior room on lowest floor - away from windows",
      "📦 Cover yourself with mattress or heavy blankets for protection",
      "🧱 Do NOT open windows - this does NOT help",
      "🚗 If driving, do NOT try to outrun tornado - seek shelter immediately",
      "🏢 If in mobile home, evacuate to sturdy building immediately",
      "🏃 If outside with no shelter, lie flat in ditch or low spot",
      "🪟 Stay away from windows and exterior walls",
      "🤝 Keep family and pets with you in safe room",
      "📱 Listen to emergency alerts and instructions",
    ],
    evacuationSteps: [
      "Wait for tornado warning to be lifted before leaving shelter",
      "Check for injuries and provide first aid",
      "Exit building carefully - watch for debris",
      "Avoid downed power lines and damaged areas",
      "Go to designated assembly points if needed",
      "Help others if you are able to do so safely",
      "Document damage with photos for insurance",
      "Listen for further instructions from authorities",
    ],
    safetyTips: [
      "Know location of safe room in your home and workplace",
      "Practice tornado drills regularly",
      "Have emergency supplies in safe room",
      "Know difference between tornado watch and warning",
      "Listen to weather alerts on radio or phone",
      "Do NOT try to outrun tornado in vehicle",
      "Do NOT open windows during tornado",
      "Stay away from windows and exterior walls",
    ],
    whatToBring: [
      "First aid kit",
      "Water",
      "Non-perishable food",
      "Flashlight and batteries",
      "Portable radio",
      "Important documents",
      "Medications",
      "Sturdy shoes and gloves",
      "Whistle for signaling",
      "Mattress or heavy blankets",
    ],
    emergencyNumber: "911",
    helplineNumber: "1-800-621-3362",
    riskLevel: "High",
  },
};
